import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const pkgPath = fileURLToPath(new URL("../package.json", import.meta.url));
const outPath = fileURLToPath(
  new URL("../src/constants/version.generated.ts", import.meta.url),
);

const pkg = JSON.parse(readFileSync(pkgPath, "utf8"));

if (typeof pkg.version !== "string" || pkg.version.length === 0) {
  console.error(`Invalid version in ${pkgPath}: ${String(pkg.version)}`);
  process.exit(1);
}

const content = [
  "// @generated by scripts/generate-version.mjs — do not edit.",
  "/**",
  ' * The SDK package version ("@lizuz/sewa-sdk") reported to the host during',
  ' * handshake via the "sdkVersion" field. Generated from "package.json" so it',
  " * can never drift from the published release.",
  " */",
  `export const RPC_CLIENT_SDK_VERSION = "${pkg.version}";`,
  "",
].join("\n");

writeFileSync(outPath, content);
console.log(
  `Generated ${outPath} with RPC_CLIENT_SDK_VERSION = "${pkg.version}"`,
);
